= createDID Function

The `createDID` function is a fundamental component of the Hashgraph DID-SDK, responsible for generating fresh DIDs for the Hedera DID method. It provides a flexible and user-friendly interface, allowing users to choose from different configurations and key management strategies.

== Features

*   **DID Creation:** Generates and registers new DIDs on the Hedera network with customizable options.
*   **Key Management:** Supports various key types and formats for DID controllers and verification methods.
*   **DID Document Generation:** Automatically generates DID Documents conforming to the DID specification.
*   **Hedera Network Support:**  Supports DID creation on the Hedera mainnet, testnet, and previewnet.
*   **Error Handling:** Provides robust error handling for invalid input, network issues, and other potential problems.
*   **TypeScript Support:** Built with TypeScript to enhance developer experience and type safety.

== Creating a DID Document

The following example demonstrates how to create a DID with minimal input using the `createDID` function:

include::did-submission-checklist.adoc[]

[source,js]
----
const clientOptions = {
  privateKey: "0x...", // Replace with your Hedera account private key
  accountId: "0.0.0....", // Replace with your Hedera account ID
  network: "testnet",
};

const { did, didDocument, privateKey } = await createDID({
  clientOptions,
});
----

In this example, the `createDID` function automatically initializes a new key pair for the DID owner. A Hedera `Client` instance is configured with essential parameters, including the Hedera account private key, account ID, and network. The function then returns the generated private key, the newly created DID, and its corresponding DID document.

=== With a Custom Controller

To modify the `controller` of a newly created DID, you can specify the desired controller as an argument to the `createDID` function. However, the provided controller must be a valid DID according to the Hedera method and must be active.

[source,js]
----
const clientOptions = {
  privateKey: "0x...", // Replace with your Hedera account private key
  accountId: "0.0.0....", // Replace with your Hedera account ID
  network: "testnet",
};

const { did, didDocument } = await createDID({
  controller: "did:hedera:mainnet:...", // Replace with your desired DID controller
}, { clientOptions });
----
In this example, the `controller` property is used to specify the desired controller for the newly created DID. The `clientOptions` object is still used to configure the Hedera `Client` instance.

=== With a Topic-Specific DID

In certain cases, it may be desirable to create a DID associated with a specific topic. This can be achieved by providing the relevant Topic ID to the `createDID` function. It is important to ensure that the `Client` or `Publisher` being passed has the necessary permissions to submit content to that topic.

[source,js]
----
const { did, didDocument } = await createDID({
  topicId: "0.0.0...", // Replace with your desired topic ID
  client,
});
----

== References

* xref:04-implementation/components/createDID-api.adoc[`createDID` API Reference]
* xref:04-implementation/components/signer-api.adoc[`Signer` API Reference]
* xref:04-implementation/components/publisher-api.adoc[`Publisher` API Reference]