= deactivateDID Function

The `deactivateDID` function is a core component of the Hashgraph DID SDK, responsible for deactivating existing DIDs for the Hedera DID method. This action effectively revokes the DID, making it unusable for future operations.

== Features

*   **DID Deactivation:** Deactivates registered DIDs on the Hedera network, revoking their validity.
*   **Secure Deactivation:**  Ensures secure and verifiable deactivation by leveraging the Hedera Consensus Service (HCS).
*   **DID Document Update:**  Updates the DID Document to reflect the deactivated status of the DID.
*   **Hedera Network Support:** Supports DID deactivation on the Hedera mainnet and testnet.
*   **Error Handling:** Provides robust error handling for invalid input, network issues, and other potential problems.
*   **TypeScript Support:** Built with TypeScript to enhance developer experience and type safety.

== Deactivating a DID Document

The following examples demonstrate how to deactivate a DID document using the `deactivateDID` function in different scenarios.

=== With Client Options

You can customize the Hedera network and account used for deactivating the DID by providing `clientOptions` to the `deactivateDID` function.

[source,js]
----
const clientOptions = {
  privateKey: "0x...", // Replace with your Hedera account private key
  accountId: "0.0.0....", // Replace with your Hedera account ID
  network: "testnet",
};

await deactivateDID(did, { clientOptions });
----

In this example, `deactivateDID` takes the DID to be deactivated and an object containing the `clientOptions`. This configuration object should include the necessary information to interact with the Hedera network, such as the private key, account ID, and network.

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/deactivateDID-with-client-options.ts[example] in the source code.**

=== With a Hedera Client

You can provide a Hedera `Client` instance directly to the `deactivateDID` function. This allows for more fine-grained control over the client configuration and network interaction.

[source,js]
----
const client = Client.forTestnet();
client.setOperator(accountId, privateKey);

await deactivateDID(did, { client });
----

In this example, a pre-configured Hedera `Client` instance is passed to the `deactivateDID` function.

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/deactivateDID-with-a-client.ts[example] in the source code.**


== References

* xref:04-implementation/components/deactivateDID-api.adoc[`deactivateDID` API Reference]