== Build a DID Update operation [[build-did-update-operation]]

The `DIDUpdateBuilder` class is used to build a DID Update operation. This class provides a set of methods to add verification methods, services, and other properties to a DID Document. To publish the update, the `DIDUpdateBuilder` must build operations to be passed to the xref:04-implementation/components/updateDID-guide.adoc[`updateDID`] function.


=== Managing verification methods
Verification methods are used to prove the authenticity of a DID Document. The xref:04-implementation/components/didUpdateBuilder-api.adoc#method-addVerificationMethod[`addVerificationMethod`] method is used to add a verification method to the DID Document. The method accepts a xref:04-implementation/components/didUpdateBuilder-api.adoc#VerificationMethod[`VerificationMethod`] object as an argument.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addVerificationMethod({
    id: "#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
  })
  .build();
----

You can add multiple verification methods to a DID Document by calling the `addVerificationMethod` method multiple times.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addVerificationMethod({
    id: "#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
  })
  .addVerificationMethod({
    id: "#key-2",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Km...",
  })
  .build();
----

To remove a verification method from a DID Document, use the xref:04-implementation/components/didUpdateBuilder-api.adoc#method-removeVerificationMethod[`removeVerificationMethod`] method. The method accepts the ID of the verification method to remove as an argument.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .removeVerificationMethod("#key-1")
  .build();
----

=== Managing services
Services are used to provide additional information about a DID Document. The xref:04-implementation/components/didUpdateBuilder-api.adoc#method-addService[`addService`] method is used to add a service to the DID Document. The method accepts a xref:04-implementation/components/didUpdateBuilder-api.adoc#Service[`Service`] object as an argument.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addService({
    id: "#service-1",
    type: "LinkedDomains",
    serviceEndpoint: "https://example.com",
  })
  .build();
----

You can add multiple services to a DID Document by calling the `addService` method multiple times.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addService({
    id: "#service-1",
    type: "LinkedDomains",
    serviceEndpoint: "https://example.com",
  })
  .addService({
    id: "#service-2",
    type: "LinkedDomains",
    serviceEndpoint: "https://example.org",
  }) 
  .build();
----

To remove a service from a DID Document, use the xref:04-implementation/components/didUpdateBuilder-api.adoc#method-removeService[`removeService`] method. The method accepts the ID of the service to remove as an argument.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .removeService("#service-1")
  .build();
----

=== Managing verification relationships
A verification relationship is used to express the relationship between a verification method and a DID subject. There are many types of verification relationships, such as authentication, assertion, key agreement, capability delegation, and capability invocation. Each verification relationship has a specific purpose and usage.

To add or remove a verification relationship, you can use methods for each type of relationship. List of methods is available in the xref:04-implementation/components/didUpdateBuilder-api.adoc#methods[`DIDUpdateBuilder` API Reference].

Example of adding a verification relationship:

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addCapabilityInvocationMethod({
    id: "#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
  })
  .addAuthenticationMethod({
    id: "#key-2",
    publicKeyMultibase: "z6Km...",
  })
  .build();
----

Also you can remove a verification relationship by using the corresponding method. For example, to remove a capability invocation method:

[source,js]
----
const builder = new DIDUpdateBuilder()
  .removeCapabilityInvocationMethod("#key-1")
  .build();
----

A verification relationship can be added as an alias for a already existing verification method. In this case, you can pass the ID of the verification method as a string.

[source,js]
----
const builder = new DIDUpdateBuilder()
  .addCapabilityInvocationMethod("#key-1")
  .build();
----