= resolveDID Function

The `resolveDID` function is a core component of the Hashgraph DID SDK. It allows you to resolve a Decentralized Identifier (DID) registered on the Hedera network and retrieve its corresponding DID Document. This function handles the retrieval and cryptographic verification of the DID Document, ensuring its authenticity and integrity.

== Resolving a DID Document

The following examples demonstrate how to use the `resolveDID` function to retrieve a DID Document in different formats.

=== As JSON-LD (Default)

This example shows how to resolve a DID and retrieve its corresponding DID Document in JSON-LD format.

[source, typescript]
----
import { resolveDID } from "@hashgraph-did-js-sdk/resolver";

const did = "did:hedera:testnet:z6Mkhj..."; // Replace with the DID you want to resolve

async function main() {
  try {
    const didDocument = await resolveDID(did); 
    console.log(didDocument); 
  } catch (error) {
    console.error("Error resolving DID:", error);
  }
}

main();
----

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/resolveDID-as-json-ld.ts[example] in the source code.**

=== As JSON

This example shows how to resolve a DID and retrieve its corresponding DID Document in JSON format.

[source, typescript]
----
import { resolveDID } from "@hashgraph-did-js-sdk/resolver";

const did = "did:hedera:testnet:z6Mkhj..."; // Replace with the DID you want to resolve

async function main() {
  try {
    const didDocument = await resolveDID(did, "application/did+json");
    console.log(didDocument);
  } catch (error) {
    console.error("Error resolving DID:", error);
  }
}

main();
----

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/resolveDID-as-json.ts[example] in the source code.**

=== With Full Metadata

This example shows how to resolve a DID and retrieve its corresponding DID Document with full DID Resolution metadata.

[source, typescript]
----
import { resolveDID } from "@hashgraph-did-js-sdk/resolver";

const did = "did:hedera:testnet:z6Mkhj..."; // Replace with the DID you want to resolve

async function main() {
  try {
    const didDocument = await resolveDID(
      did,
      'application/ld+json;profile="https://w3id.org/did-resolution"'
    ); 
    console.log(didDocument);
  } catch (error) {
    console.error("Error resolving DID:", error);
  }
}

main();
----

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/resolveDID-with-full-metadata.ts[example] in the source code.**

=== As CBOR

This example shows how to resolve a DID and retrieve its corresponding DID Document in CBOR format.

[source, typescript]
----
import { resolveDID } from "@hashgraph-did-js-sdk/resolver";

const did = "did:hedera:testnet:z6Mkhj..."; // Replace with the DID you want to resolve

async function main() {
  try {
    const didDocumentUintArray = await resolveDID(
      did,
      'application/did+cbor'
    ); 
    console.log(didDocumentUintArray);
  } catch (error) {
    console.error("Error resolving DID:", error);
  }
}

main();
----

**See a full running link:https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js/blob/main/examples/resolveDID-as-cbor.ts[example] in the source code.**

== References

* xref:04-implementation/components/resolveDID-api.adoc[`resolveDID` API Reference]