= `DIDUpdateBuilder` class

The following documents serve as a reference for the `DIDUpdateBuilder` class, offering insight into the function's associated APIs.
The `DIDUpdateBuilder` class provides a fluent interface to build a DID update operation that can be used to update a DID Document.


== Usage examples

* xref:components/did-update-builder/guide.adoc[Build a DID Update operation]


== Installation

`DIDUpdateBuilder` function is part of the `@hashgraph-did-sdk/basic` package. Install the package using your preferred package manager:

* Using npm:
[source,bash]
----
npm install @hashgraph-did-sdk/basic
----

* Using yarn:
[source,bash]
----
yarn add @hashgraph-did-sdk/basic
----

* Using pnpm:
[source,bash]
----
pnpm add @hashgraph-did-sdk/basic
----


== Import

Import a package using the CommonJS or ES module syntax.

[source,js]
----
// import ESM
import { DIDUpdateBuilder } from '@hashgraph-did-sdk/basic';

// import CJS
const { DIDUpdateBuilder } = require('@hashgraph-did-sdk/basic');
----


== Type

[source,js]
----
class DIDUpdateBuilder {};
----


== Methods [[methods]]

=== `public addVerificationMethod` [[method-addVerificationMethod]]
[source,js]
----
public addVerificationMethod(method: VerificationMethod): DIDDocumentBuilder {}
----

Adds a verification method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A verification method is a public key that can be used to authenticate or authorize interactions with the DID subject.

Parameters::
* `method`: The xref:VerificationMethod[VerificationMethod] object to be added.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeVerificationMethod` [[method-removeVerificationMethod]]
[source,js]
----
public removeVerificationMethod(methodId: string): DIDDocumentBuilder {}
----

Removes a verification method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the verification method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addAuthenticationMethod` [[method-addAuthenticationMethod]]
[source,js]
----
public addAuthenticationMethod(methodOrId: VerificationMethod | string): DIDDocumentBuilder {}
----

Adds an authentication method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A authentication method is a public key that can be used to authenticate the DID subject.

Parameters::
* `methodOrId`: The xref:VerificationMethod[VerificationMethod] object or the identifier of the verification method as a source.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeAuthenticationMethod` [[method-removeAuthenticationMethod]]
[source,js]
----
public removeAuthenticationMethod(methodId: string): DIDDocumentBuilder {}
----

Removes an authentication method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the authentication method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addAssertionMethod` [[method-addAssertionMethod]]
[source,js]
----
public addAssertionMethod(methodOrId: VerificationMethod | string): DIDDocumentBuilder {}
----

Adds an assertion method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A assertion method is a public key that can be used to express claims, such as for the purposes of issuing a Verifiable Credential

Parameters::
* `methodOrId`: The xref:VerificationMethod[VerificationMethod] object or the identifier of the verification method as a source.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeAssertionMethod` [[method-removeAssertionMethod]]
[source,js]
----
public removeAssertionMethod(methodId: string): DIDDocumentBuilder {}
----

Removes an assertion method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the assertion method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addKeyAgreementMethod` [[method-addKeyAgreementMethod]]
[source,js]
----
public addKeyAgreementMethod(methodOrId: VerificationMethod | string): DIDDocumentBuilder {}
----

Adds a key agreement method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A key agreement method is a public key that can be used to derive a shared secret for secure communication.

Parameters::
* `methodOrId`: The xref:VerificationMethod[VerificationMethod] object or the identifier of the verification method as a source.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeKeyAgreementMethod` [[method-removeKeyAgreementMethod]]
[source,js]
----
public removeKeyAgreementMethod(methodId: string): DIDDocumentBuilder {}
----

Removes a key agreement method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the key agreement method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addCapabilityInvocationMethod` [[method-addCapabilityInvocationMethod]]
[source,js]
----
public addCapabilityInvocationMethod(methodOrId: VerificationMethod | string): DIDDocumentBuilder {}
----

Adds a capability invocation method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A capability invocation method is a public key that can be used to invoke a cryptographic capability, such as the authorization to update the DID Document.

Parameters::
* `methodOrId`: The xref:VerificationMethod[VerificationMethod] object or the identifier of the verification method as a source.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeCapabilityInvocationMethod` [[method-removeCapabilityInvocationMethod]]
[source,js]
----
public removeCapabilityInvocationMethod(methodId: string): DIDDocumentBuilder {}
----

Removes a capability invocation method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the capability invocation method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addCapabilityDelegationMethod` [[method-addCapabilityDelegationMethod]]
[source,js]
----
public addCapabilityDelegationMethod(methodOrId: VerificationMethod | string): DIDDocumentBuilder {}
----

Adds a capability delegation method to the DID document. If a verification method with the same ID already exists, it will be replaced.
A capability delegation method is a public key that can be used to delegate authority to another party.

Parameters::
* `methodOrId`: The xref:VerificationMethod[VerificationMethod] object or the identifier of the verification method as a source.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeCapabilityDelegationMethod` [[method-removeCapabilityDelegationMethod]]
[source,js]
----
public removeCapabilityDelegationMethod(methodId: string): DIDDocumentBuilder {}
----

Removes a capability delegation method from the DID document by its identifier.

Parameters::
* `methodId`: The identifier of the capability delegation method to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public addService` [[method-addService]]
[source,js]
----
public addService(service: Service): DIDDocumentBuilder {}
----

Adds a service to the DID document. If a service with the same ID already exists, it will be replaced.

Parameters::
* `service`: The xref:Service[Service] object to be added.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public removeService` [[method-removeService]]
[source,js]
----
public removeService(serviceId: string): DIDDocumentBuilder {}
----

Removes a service from the DID document by its identifier.

Parameters::
* `serviceId`: The identifier of the service to be removed.

Returns::
The current `DIDDocumentBuilder` instance for method chaining.

=== `public toJSON` [[method-toJSON]]
[source,js]
----
public toJSON(): Object {}
----

Converts the `DIDDocumentBuilder` instance to a JSON object.

Returns::
The JSON representation of the `DIDDocumentBuilder` instance.

=== `static fromJSON` [[method-fromJSON]]
[source,js]
----
public static fromJSON(json: Object): DIDDocumentBuilder {}
----

Creates a new `DIDDocumentBuilder` instance from a JSON object.

Parameters::
* `json`: The JSON object to create the `DIDDocumentBuilder` instance from.

Returns::
A new `DIDDocumentBuilder` instance created from the JSON object.

=== `static empty` [[method-empty]]
[source,js]
----
public static empty(): DIDDocumentBuilder {}
----

Creates an empty `DIDDocumentBuilder` instance.

Returns::
An empty `DIDDocumentBuilder` instance.

== Releated interfaces

=== `VerificationMethod` interface [[VerificationMethod]]
Represents a verification method that can be added to a DID document.

[source,js]
----
interface VerificationMethod {
  id: string;
  type: 'Ed25519VerificationKey2020';
  controller: string;
  publicKeyMultibase: string;
}
----

Properties::
* `id`: The identifier of the verification method, e.g., `#key-1`.
* `type`: The type of verification method, e.g., `Ed25519VerificationKey2020`.
* `controller`: The DID that controls the verification method.
* `publicKeyMultibase`: The public key in multibase format.


=== `Service` interface [[Service]]
Represents a service that can be added to a DID document.

[source,js]
----
interface Service {
  id: string;
  type: string;
  serviceEndpoint: string;
}
----

Properties::
* `id`: The identifier of the service, e.g., `#service-1`.
* `type`: The type of service, e.g., `MessagingService`.
* `serviceEndpoint`: The service endpoint URL.


== Source code
The implementation of the function can be found https://github.com/Swiss-Digital-Assets-Institute/hashgraph-did-sdk-js[*here*]. In this source, the exact details of the function are provided, as well as an explanation of its operation in cases where further clarification is required.

== Dependencies

image::https://www.planttext.com/api/plantuml/svg/hPJ1Ki8m48RlVOeSgqvVW1Ce7j113epUqsJ1nJJf9DlETDHtDpGm51gb39uwsTt-_xURTiUEkAMgKAmg9IV89Ceihr19i9c44hG4BH1SCfrDNzkI-v1bjrd6ti3Y2WKdD7eEz6val6u9jaO1II8KTuxrQZuJnjWTyp24Wa5HKfFUi56lC9HnAVl6QTqBZI9ylwjQA4mD4M7qGakogDT_8krwJ5ruZlPDdtFSlpVGPbBHEsWwHkIHOAnxzdNM8a15NGOIFaCpMLk0mWka7vt3LKH7gaDdvVnbTCTqVBvkGYVQ0v4UUCbpL4ZD51IiM-TKH89NmKLTBYQSwTg8Ky93y9y8Eov32CayBHSlxNPOv1iG5C8hQuesiN5Rif2AgdmdIOAQmAwuW5WBxJ8A60nbvo2C9ckK2YYxO5db2eN_EkUL8iovWqwIcXAsXWU_tTz-eSbkfpngMHglvIN7VZFxjVq3[diagram,svg]
