= Build a DID Update operation

The `DIDUpdateBuilder` class is used to build a DID Update operation. This class provides a set of methods to add verification methods, services, and other properties to a DID Document. To publish the update, the `DIDUpdateBuilder` instance must be passed to the xref:components/update-did/guide.adoc[`updateDID`] function.


== Managing verification methods
Verification methods are used to prove the authenticity of a DID Document. The xref:components/did-update-builder/api.adoc#method-addVerificationMethod[`addVerificationMethod`] method is used to add a verification method to the DID Document. The method accepts a xref:components/did-update-builder/api.adoc#VerificationMethod[`VerificationMethod`] object as an argument.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addVerificationMethod({
    id: "did:hedera:mainnet:...#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
    type: "Ed25519VerificationKey2020",
  });
----

You can add multiple verification methods to a DID Document by calling the `addVerificationMethod` method multiple times.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addVerificationMethod({
    id: "did:hedera:mainnet:...#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
    type: "Ed25519VerificationKey2020",
  })
  .addVerificationMethod({
    id: "did:hedera:mainnet:...#key-2",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Km...",
    type: "Ed25519VerificationKey2020",
  });
----

To remove a verification method from a DID Document, use the xref:components/did-update-builder/api.adoc#method-removeVerificationMethod[`removeVerificationMethod`] method. The method accepts the ID of the verification method to remove as an argument.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .removeVerificationMethod("did:hedera:mainnet:...#key-1");
----

== Managing services
Services are used to provide additional information about a DID Document. The xref:components/did-update-builder/api.adoc#method-addService[`addService`] method is used to add a service to the DID Document. The method accepts a xref:components/did-update-builder/api.adoc#Service[`Service`] object as an argument.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addService({
    id: "did:hedera:mainnet:...#service-1",
    controller: "did:hedera:mainnet:...",
    serviceEndpoint: "https://example.com",
  });
----

You can add multiple services to a DID Document by calling the `addService` method multiple times.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addService({
    id: "did:hedera:mainnet:...#service-1",
    controller: "did:hedera:mainnet:...",
    serviceEndpoint: "https://example.com",
  })
  .addService({
    id: "did:hedera:mainnet:...#service-2",
    controller: "did:hedera:mainnet:...",
    serviceEndpoint: "https://example.org",
  });
----

To remove a service from a DID Document, use the xref:components/did-update-builder/api.adoc#method-removeService[`removeService`] method. The method accepts the ID of the service to remove as an argument.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .removeService("did:hedera:mainnet:...#service-1");
----

== Managing verification relationships
A verification relationship is used to express the relationship between a verification method and a DID subject. There are many types of verification relationships, such as authentication, assertion, key agreement, capability delegation, and capability invocation. Each verification relationship has a specific purpose and usage.

To add or remove a verification relationship, you can use methods for each type of relationship. List of methods is available in the xref:components/did-update-builder/api.adoc#methods[`DIDUpdateBuilder` API Reference].

Example of adding a verification relationship:

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addCapabilityInvocationMethod({
    id: "did:hedera:mainnet:...#key-1",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Mk...",
    type: "Ed25519VerificationKey2020",
  })
  .addAuthenticationMethod({
    id: "did:hedera:mainnet:...#key-2",
    controller: "did:hedera:mainnet:...",
    publicKeyMultibase: "z6Km...",
    type: "Ed25519VerificationKey2020",
  });
----

Also you can remove a verification relationship by using the corresponding method. For example, to remove a capability invocation method:

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .removeCapabilityInvocationMethod("did:hedera:mainnet:...#key-1");
----

A verification relationship can be added as an alias for a already existing verification method. In this case, you can pass the ID of the verification method as a string.

[source,js]
----
const builder = DIDUpdateBuilder
  .empty()
  .addCapabilityInvocationMethod("did:hedera:mainnet:...#key-1");
----


== References

* xref:components/did-update-builder/api.adoc[`DIDUpdateBuilder` API Reference]
* xref:components/update-did/guide.adoc[`updateDID` function guide]
