@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Hiero DID SDK Component View

Person_Ext(developer, "dApp Developer", "Builds dApps with decentralized identity (not just identifiers)")

System_Boundary(c1, "Hiero DID SDK") {

  Component(registrar, "Registrar", "DID create, update, and deactivate operations")
  Component(resolver, "Resolver", "Resolves DID Document")
  Component(hcsService, "HcsService", "Manages Hedera Consensus Service objects")
  Component(anoncredsRegistry, "HederaAnoncredsRegistry", "Manages AnonCreds schemas, credential defs, revocation registries")

  Component(signer, "Signer", "Signs DID Message")
  Component(verifier, "Verifier", "Verifies DID Message")

  Component(publisher, "Publisher", "Signs & Publishes Transaction")

  Component(hashicorpSigner, "HashiCorp Signer", "Signs DID Message")
  Component(hashicorpVerifier, "HashiCorp Verifier", "Verifies DID Message")

  Component(hcsTopicService, "HcsTopicService", "Manages Hedera Consensus Service topics")
  Component(hcsMessageService, "HcsMessageService", "Sends and retrieves messages from topics")
  Component(hcsFileService, "HcsFileService", "Stores and resolves files according to HCS-1 standard")
}

System_Ext(hashicorp, "HashiCorp Vault", "External KMS used by Vault signer/verifier")

System_Ext(topic, "Hedera Consensus Service", "Service providing decentralized, auditable logs of immutable and timestamped events (messages)")
System_Ext(hedera, "Hedera Node", "Gateway to the Hedera network")

Rel(developer, registrar, "Uses")
Rel(developer, resolver, "Uses")
Rel(developer, hcsService, "Uses")
Rel(developer, anoncredsRegistry, "Uses")

Rel(registrar, signer, "Uses")
Rel(registrar, verifier, "Uses")

Rel(registrar, publisher, "Uses")

Rel(registrar, hashicorpSigner, "Uses")
Rel(registrar, hashicorpVerifier, "Uses")

Rel(hashicorpSigner, hashicorp, "Uses")
Rel_R(hashicorpVerifier, hashicorp, "Uses")

Rel(publisher, topic, "Publishes", "Signed Transaction")
Rel(resolver, topic, "Retrieves", "DID Document")

Rel(hcsService, hcsTopicService, "Uses")
Rel(hcsService, hcsMessageService, "Uses")
Rel(hcsService, hcsFileService, "Uses")

Rel(hcsMessageService, topic, "Publishes and retrieves messages")
Rel(hcsFileService, topic, "Publishes and retrieves files")
Rel(hcsTopicService, topic, "Manages topics")

Rel_L(anoncredsRegistry, hcsService, "Uses")

Rel(topic, hedera, "Communicates with")


@enduml
