@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Hiero DID SDK Container View

Person_Ext(developer, "dApp Developer", "Builds dApps with decentralized identity (not just identifiers)")

System_Boundary(c1, "Hiero DID SDK") {
 Container(core, "Module", "core, messages, lifecycle, registrar, resolver, signer-internal, verifier-internal, signer-hashicorp-vault, verifier-hashicorp-vault, publisher-internal, client, hcs, cache, crypto, zstd, anoncreds")
}

System_Ext(hashicorp, "HashiCorp Vault", "External KMS used by Vault signer/verifier")

System_Ext(topic, "Hedera Consensus Service", "Service providing decentralized, auditable logs of immutable and timestamped events (messages)")

System_Ext(hedera, "Hedera Node", "Gateway to the Hedera network")

Rel(developer, core, "Uses")
Rel(core, topic, "Uses")
Rel(core, hashicorp, "Uses")
Rel(topic, hedera, "Communicates with")

@enduml
