@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Hiero DID SDK Container View

Person_Ext(developer, "dApp Developer", "Builds dApps with decentralized identities")

System_Boundary(c1, "Hiero DID SDK") {
 Container(core, "Core Module", "DID create, update, and deactivate operations; DID message signing and verification; transaction signing and execution")
}

System_Ext(topic, "Hedera Topic Service", "Provides publish/subscribe mechanism for DID communication")
System_Ext(hedera, "Hedera Node", "Gateway to the Hedera network")

Rel(developer, core, "Uses")
Rel(core, topic, "Uses")
Rel(topic, hedera, "Communicates with")

@enduml