=== Name
Transaction and Operation should be able to sign with external keys
  
=== Description
Any operation or transaction performed using the SDK should be able to be signed with external keys. Signing a transaction or operation with external keys involves using a key pair that is not managed by the SDK. This way, we will be able to sign transactions or operations with keys stored in a hardware wallet or any other external key management system.

=== Status
Draft

=== Acceptance Criteria
* The SDK should provide give ability to sign a transaction or operation with external keys.
* The SDK should provide a asynchronous method to sign a transaction or operation.

=== References
* https://www.vaultproject.io/use-cases/key-management
* https://aws.amazon.com/kms/
* https://bladewallet.io/

=== Diagrams
[mermaid]
....
sequenceDiagram
    participant SDK
    participant CLT as Client
    participant SIG as KMS/Wallet
    
    CLT->>SDK: Create Transaction
    SDK-->>CLT: Signature required
    CLT->>SIG: Sign Transaction
    SIG-->>CLT: Signature
    CLT->>SDK: Add Signature
    SDK-->>CLT: Transaction Signed
....
