=== Name
Manage Verification Relationships
  
=== Description
The SDK should provide an option to manage the verification relationships of a DID Document. Clients should be able to add and revoke verification relationships from the DID Document. Verification relationships are used to establish a trust relationship between a DID and a verification method. Supported verification relationships include `authentication`, `assertionMethod`, `keyAgreement`, `capabilityInvocation`, and `capabilityDelegation`. Accepting aliases for these relationships should be presented. The SDK should be compatible with the Hedera DID method specification.

=== Status
Draft

=== Acceptance Criteria
* The SDK should provide an option to add a verification relationships to a DID Document.
* The SDK should provide an option to revoke a verification relationships from a DID Document.
* The SDK should support following verification relationships:
** authentication
** assertionMethod
** keyAgreement
** capabilityInvocation
** capabilityDelegation
* The SDK should support following Key Management modes: 
** Internal Secret Mode
** External Secret Mode
** Client-managed Secret Mode

=== References
* https://identity.foundation/did-registration/#key-management
* https://www.w3.org/TR/did-core/#verification-relationships
* https://identity.foundation/did-registration/#create
* https://github.com/hashgraph/did-method/
