import { DIDDocument } from '@swiss-digital-assets-institute/core';
import { PrivateKey } from '@hashgraph/sdk';
import {
  OperationState,
  SigningRequest,
  CommonRegistrarOptions,
} from '../interfaces';
import { TopicReader } from '@swiss-digital-assets-institute/resolver';

export interface DeactivateDIDOptions extends CommonRegistrarOptions {
  /**
   * The DID to deactivate
   */
  did: string;

  /**
   * The private key to use to sign the deactivate operation.
   * If Signer is provided, this field is ignored.
   */
  privateKey?: string | PrivateKey;
}

export interface DeactivateDIDResult {
  /**
   * The DID that was deactivated
   */
  did: string;

  /**
   * The updated DID document after deactivation
   */
  didDocument: DIDDocument;
}

export interface DeactivateDIDRequest {
  /**
   * The state of the current operation.
   */
  state: OperationState;

  /**
   * The signing request for the operation.
   */
  signingRequest: SigningRequest;
}

export interface GenerateDeactivateDIDRequestOptions {
  /**
   * The DID to deactivate
   */
  did: string;

  /**
   * The topic reader to use to read messages from the Hedera network topic.
   */
  topicReader?: TopicReader;
}

export interface SubmitDeactivateDIDRequestOptions
  extends CommonRegistrarOptions {
  /**
   * Current state of the operation, generated by the `generateDeactivateDIDRequest` function
   */
  state: OperationState;

  /**
   * The signature of the signing request
   */
  signature: Uint8Array;
}
