@startuml deactivate-did-dependencies
DIDRegistrarUtils --> Signer
DIDRegistrarUtils --> Publisher
DIDRegistar --> DIDRegistrarUtils
DeactivateDIDResult --> DIDDocument
DIDRegistar --> Providers
DIDRegistar --> Options
Providers --> ClientOptions
DIDRegistar --> DeactivateDIDResult
ClientOptions --> PrivateKey
DeactivateDIDResult --> PrivateKey
Options --> PrivateKey
Publisher --> Transaction
Publisher --> TransactionReceipt
Providers --> Client


class DIDRegistar {
   + deactivate(options: Options, providers: Providers) : DeactivateDIDResult
}

class DIDRegistrarUtils {
   # getPublisher() : Publisher
   # getSigner() : Signer
}

interface DeactivateDIDResult {
   String did
   DIDDocument didDocument
}

interface Providers {
   Signer signer?
   Publisher publisher?
   Client | ClientOptions client
}

interface ClientOptions {
   String | PrivateKey privateKey
   String accountId
   String network
}

interface Options {
   String did
   String | PrivateKey privateKey
}


abstract class Signer {
   {abstract} + String publicKey
   {abstract} + sign(message: Uint8Array) : Uint8Array
}

abstract class Publisher {
   {abstract} + Client client
   {abstract} + publish(transaction: Transaction) : TransactionReceipt
}

interface DIDDocument {
   String id
   String controller
   VerificationMethod[] verificationMethod
}

class PrivateKey << (S,#FF7700) Hedera SDK >>
class Transaction << (S,#FF7700) Hedera SDK >>
class TransactionReceipt << (S,#FF7700) Hedera SDK >>
class Client << (S,#FF7700) Hedera SDK >>
@enduml