@startuml
class HcsTopicService {
  - cacheService?: HcsCacheService
  - client: Client
  + constructor(client: Client, cache?: CacheConfig | Cache | HcsCacheService)
  + createTopic(props?: CreateTopicProps): Promise<string>
  + updateTopic(props: UpdateTopicProps): Promise<void>
  + deleteTopic(props: DeleteTopicProps): Promise<void>
  + getTopicInfo(props: GetTopicInfoProps): Promise<TopicInfo>
}
@enduml
