@startuml
class Signer {
  - privateKey?: string
  + constructor(privateKey?: string)
  + {static} generate(): Signer
  + publicKey(): Promise<string>
  + publicKeyInstance(): Promise<PublicKey>
  + sign(message: Uint8Array): Promise<Uint8Array>
  + signTransaction(transaction: Transaction): Promise<Transaction>
  + verify(message: Uint8Array, signature: Uint8Array): Promise<boolean>
}
@enduml