@startuml
interface VerificationMethodProperties {
  + verificationMethod: VerificationMethod[]
  + authentication?: string[] | VerificationMethod[]
  + assertion
  + capabilityInvocation?: string[]
}
@enduml