= deactivateDID function

This document provides a concise reference for the `deactivateDID` function within the Hedera DID SDK for JavaScript.

== Function Signature

The `deactivateDID` function allows you to deactivate an existing DID.

[source,js]
----
function deactivateDID(
  options: DeactivateDIDOptions,
  providers: Providers
): Promise<DeactivateDIDResult>;
----

== Parameters

The function accepts the following parameters:

*   **`providers`:** (Required) An object encapsulating configuration parameters for interacting with the Hedera network.
*   **`options`:** (Required) An object containing the DID to deactivate.

=== providers Parameter

The table below details the structure of the `providers` parameter.

[cols="1,1,3",options="header",frame="ends"]
|===
|Name
|Type
|Description

|providers
|`Providers`
|An object containing a Hedera Client, a cryptographic Signer, and a transaction Publisher (refer to <<providers-data-types>> for details).
|===


=== options Parameter

[cols="1,1,3",options="header",frame="ends"]
|===
|Name
|Type
|Description

|did
|`string`
|The DID string of the Decentralized Identifier to deactivate.

|privateKey?
|`string` \| PrivateKey`
|A private key (in DER format) or a `PrivateKey` object used to generate a xref:04-implementation/components/signer/guide.adoc[Signer] for signing the DID deactivate message. If neither this parameter nor `signer` (in the `providers` parameter) is specified, a new key pair is generated.
|===

== Data Types

This section elaborates on the data types employed within the `providers` parameter.

[[providers-data-types]]
=== Providers Type

To utilize this type, at least one of the following must be defined: `client` or `publisher`. If both are provided, `publisher` takes precedence.

The table below provides a detailed description of the `Providers` type.

[cols="1,1,3",options="header",frame="ends"]
|===
|Name
|Type
|Description

|clientOptions?
|`ClientOptions`
|Configuration options for instantiating a Hedera Client.

|client?
|`Client`
|An instance of a Hedera Client.

|signer?
|`Signer`
|An instance of a xref:04-implementation/components/signer/guide.adoc[Signer]. If not provided, a private key must be specified in the `options` parameter to sign the DID creation message; otherwise, an exception will be thrown.

|publisher?
|`Publisher`
|An instance of a xref:04-implementation/components/publisher/guide.adoc[Publisher] responsible for submitting the DID creation transaction to the Hedera network.
|===

== Return Value

Upon successful execution, the function returns a Promise that resolves to a `DeactivateDIDResult` object.

[cols="1,1,3",options="header",frame="ends"]
|===
|Name
|Type
|Description

|did
|`string`
|The deactivated DID.

|didDocument
|`DIDDocument`
|An empty DID Document that represents a deactivated DID.
|=== 

== Errors

The following table enumerates the exceptions that may arise during the execution of the `deactivateDID` function.

[cols="1,1",options="header",frame="ends"]
|===
|Exception class
|Description 

|`DIDNotFoundError`
|Thrown when the DID is not found.

|`InvalidPrivateKeyError`
|Thrown when the private key is not a valid DER string.

|`InvalidSignerError`
|Thrown when the signer is not a valid Signer instance.

|`InvalidPublisherError`
|Thrown when the publisher is not a valid Publisher instance.
|=== 

== Class Diagram

The following class diagram provides a visual representation of the relationships between key classes and interfaces involved in the `deactivateDID` function.

image::https://www.planttext.com/api/plantuml/svg/bLLDJ-Cm4BtxLup49GWgSMDLePOL5TeA8H1TzhBQWt66O94waJqfGi1_ntQSnFde2av9vZtFctapLiuDSKtLDWUXaHFEKfdEKYnHfQY4HCDMwzKTPjAGvlgUP6vWDbl0HcOAzHxmjdh8fNcASQuzCkAp2o_huwRAgM6j2b5jKT4emwqkTZ95RKR8JKcoK8Qr31-zoALDqs33CmDrrcC7FRcpb2jydImrWlUSQitmm6_DbU72CVSZToXGbZJP2MDCvDmOY5jvOm1m54QObCsn6nrgcdUsmNjZr36qn6L4E8Jvo9QFaMWxRozz01bIsqxYKdGxqE3rodWmR8zDAnMXVkG2XvfruWrfgJAmI-c-ehrmeNP7BDGPRhjgNfTzXSw3EhSl0en_B7sITY1by-RZjVFMkVvwY7eW_IvwZBY7z-aQ8mONegWKhTCeff1U2ltS5vbABmf5kiZpK7A8Kb5AiKwNNwZ3AZ3-u2Oh2Eff1uUyp5k3VTX52wcyIo8qqICuKvCj6iCpdCEzBVt7Jwtvgnj-z-Kq1vBT2CQgOGp1zY4QHfPGTu_cyQLoqXDth6Til62nkJATTDe5_w2MZr9mb_CQwQb8__w3tIZONQ78_RCpI3R71vUNfwSd9uVm2-roSjYihc2n2Eoeuc_IGuDVEHMC_I_ptFuHx6_Y4m00[Dependency Diagram]

== Function Implementation

The Hashgraph DID SDK provides a `deactivateDID` function within its `registrar` package. For further details, refer to the xref:06-deployment/packages/index.adoc#registrar-package[`@hashgraph-did-sdk-js/registrar`] package documentation.