= Deactivate a DID Document

DID deactivation is defined as the process of terminating and deleting a DID. Consequently, the resolved DID document is resolved empty following this operation. It should be noted that this process is irreversible.

The `deactivateDID` function is to deactivate a DID. This function submit a message with operation set to `revoke` and empty payload to DID Topic.

// Add a note about the need for the Publisher to have the necessary permissions to publish messages to the Topic.
include::../../shared//existing-did-updates-notes.adoc[]

== Deactivate DID using Private Key
The following example illustrates the process of deactivating a DID using a private key. The DID is specified as an argument, along with the private key in DER format. The client is also provided as an object, containing the necessary information for the Hedera account.

[source,js]
----
const { did, didDocument, privateKey } = await deactivateDID({
  did: "did:hedera:mainnet:...", // Replace with your desired DID
  privateKey: "0x...", // Replace with your private key in DER format
}, {
  client: {
    privateKey: "0x...", // Replace with your Hedera account private key
    accountId: "0.0.0....", // Replace with your Hedera account ID
    network: "testnet",
  },
});
----


== Deactivate a DID using a Client instance
Instead of passing options for the client, it is possible to create a Client instance and pass it as an argument. This can be achieved by creating a new instance of the Client class and passing it as an argument.

[source,js]
----
const { did, didDocument } = await deactivateDID({
  did: "did:hedera:mainnet:...", // Replace with your desired DID
  privateKey: "0x...", // Replace with your private key in DER format
}, { client });
----

== Deactivate a DID using an external key
It is possible to sign a DID Message using an external key, for example, by utilizing the services of AWS KMS or Vault by HashiCorp. This can be achieved by employing the appropriate Signer. The SDK has implementations for the more common solutions. Additionally, it is possible to create a Signer using the available interfaces. In the following example, the `KMSSigner` is used to sign the message. There is no need to provide the private key in this case.

[source,js]
----
const signer = KMSSigner({ url, credentials });
const { did, didDocument } = await deactivateDID({
  did: "did:hedera:mainnet:...", // Replace with your desired
}, { 
	signer: signer.forKey(keyId),
	client,
});
----

== References

* xref:components/operations/deactivate-did/api.adoc[`deactivateDID` API Reference]
* xref:components/signers/local-signer/signer.adoc[Signer Reference]
* xref:components/publishers/local-publisher/publisher.adoc[Publisher Reference]
* xref:components/clients/local-client/client.adoc[Client Reference]
* xref:components/signers/local-signer/signer.adoc[PrivateKey Reference]
