name: Lint Check Workflow

on:
  pull_request:

jobs:
  lint-pacakges:
    runs-on: ubuntu-latest
    name: Lint Check
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node and install dependencies
        uses: ./.github/actions/setup-npm-env

      - name: Build packages
        run: pnpm build

      - name: Run linter
        run: pnpm lint
