name: Lint Check Workflow

on:
  pull_request:

jobs:
  lint-pacakges:
    runs-on: ubuntu-latest
    name: Lint Check
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node and install dependencies
        uses: ./.github/actions/setup-npm-env

      - name: Build packages
        run: pnpm build

      - name: Run linter
        run: pnpm lint
