name: Publish Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  publish-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    name: Publish packages releases
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node and install dependencies
        uses: ./.github/actions/setup-npm-env

      - name: Publish packages
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch version
        run: |
          PACKAGE_VERSION=$(cat lerna.json | jq -r .version)
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

          if [[ "${PACKAGE_VERSION}" =~ -(alpha|beta|rc) ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Create a GitHub release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          tag: 'v${{ env.PACKAGE_VERSION }}'
          name: 'Release v${{ env.PACKAGE_VERSION }}'
          generateReleaseNotes: true
          prerelease: ${{ env.PRERELEASE }}
