name: Unit Tests Workflow

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    name: Unit Tests [Node v${{ matrix.node }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Prepare Hiero Solo
#        id: solo
#        uses: hiero-ledger/hiero-solo-action@71219540ac7f578e6ea4fc3c17575c0295e56163
#        with:
#          installMirrorNode: true

      - name: Set up Node and install dependencies
        uses: ./.github/actions/setup-npm-env
        with:
          node-version: ${{ matrix.node }}

      - name: Build packages
        run: pnpm build

      - name: Run unit tests
        timeout-minutes: 15
        env:
          HEDERA_OPERATOR_ID: ${{ secrets.HEDERA_OPERATOR_ID }}
          HEDERA_OPERATOR_KEY: ${{ secrets.HEDERA_OPERATOR_KEY }}
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: pnpm test:ci

      - name: Report coverage
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
