name: Unit Tests Workflow

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    name: Unit Tests [Node v${{ matrix.node }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --workspaces --include-workspace-root

      - name: Build packages
        run: npm run packages:build

      - name: Run unit tests
        timeout-minutes: 8
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npm run packages:test:ci

      - name: Report coverage
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
